### ISSUE TITLE
shi7 doesn't recognize *.fq files.

### ISSUE THREAD

**Issue by RRShieldsCutler** [knights-lab/shi7#41]
fastq files are only recognized if file extension = ".fastq". Files such as "Sample1_R1.fq" will throw the following error:

`Traceback (most recent call last):
  File "/project/flatiron2/sop/shi7.py", line 383, in <module>
    main()
  File "/project/flatiron2/sop/shi7.py", line 329, in main
    path_fastqs = axe_adaptors_paired_end(path_fastqs, axe_output, args.adaptor, threads=args.threads, shell=args.shell)
  File "/project/flatiron2/sop/shi7.py", line 174, in axe_adaptors_paired_end
    path_R1_fastqs, path_R2_fastqs = split_fwd_rev(input_fastqs)
  File "/project/flatiron2/sop/shi7.py", line 146, in split_fwd_rev
    raise ValueError('Error: The input directory %s must contain at least one pair of R1 & R2 fastq file!' % os.path.dirname(paths[0]))
IndexError: list index out of range`

**Comment by GabeAl** [comment]
@kaiweiang Could you make shi7.py accept ".fq" files too? They are the same as ".fastq"

Thanks!
