### ISSUE TITLE
StopIteration bug in shi7.read_fastq() was merged back into master

### ISSUE THREAD

**Issue by wigasper** [knights-lab/shi7#67]
Hi all, I'm working with Jonathan Clayton at UNO and we're looking at using Shi7 in our standard pipeline. I'm happy to help contribute to the project so if you are looking for additional help let me know. I am more than happy to make a PR to fix this but it looks like someone in the group already previously did that - let me know though if you are tight on time and I will go ahead and do this.

`read_fastq()` at line 107 of shi7.py will eventually raise `StopIteration` in newer Python versions.
This appears to have been fixed [with this commit](https://github.com/knights-lab/shi7/commit/9ab6798cf0db01fa30a1cbbef7faacf49f26a773) but then the original code was put back into master with a [subsequent merge](https://github.com/knights-lab/shi7/commit/0fc076626d80af73ba6fbd3d79d6811359fd7523).

**Comment by GabeAl** [comment]
You are correct. I merged something I definitely shouldn't have. 

https://github.com/knights-lab/shi7/issues/66

It is now causing all sorts of issues.

**Comment by GabeAl** [comment]
Okay, I've added grouper back in (which decomposed a fastq record into sequence, garbage, and qualities; and which uses zip_longest to pack them together). 

Hopefully this re-fixes the stopIteration bug. In the meantime, I have learned not to blindly trust github's auto merge conflict detection.

**Comment by wigasper** [comment]
Thanks! Much appreciated. Would it be helpful for me to set up a CI workflow to run through the unit tests on every PR?

**Comment by GabeAl** [comment]
That would be phenomenal if you had the time and willingness! Much appreciated.

**Comment by ReneKat** [comment]
Hi there, Just installed on a local MacBook Pro OSX 10.14.6.
Installed successfully via 
```
wget https://github.com/knights-lab/shi7/releases/download/v0.9.9/shi7_0.9.9_mac_release.zip
unzip shi7_*_release.zip
chmod +x ./shi7*
echo "PATH=$PWD:$PATH" >> ~/.bash_profile
. ~/.bash_profile
. ~/.bashrc
shi7.py -h
```
After running `gunzip -k` on all my gzipped fastq files, I ran 
`shi7_learning.py -i <fastq/directory. -o learnt`
and received the following error:

`Owl$ shi7_learning.py -i ../../00_Data -o learnt`

> Traceback (most recent call last):
>   File "/Users/Owl/bin/shi7.py", line 105, in read_fastq
>     title = next(fh)
> StopIteration
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/Owl/bin/shi7_learning.py", line 379, in <module>
>     main()
>   File "/Users/Owl/bin/shi7_learning.py", line 339, in main
>     filt_q, trim_q = trimmer_learning(fastq_paths)
>   File "/Users/Owl/bin/shi7_learning.py", line 185, in trimmer_learning
>     for gen in fq_gen:
> RuntimeError: generator raised StopIteration

Thanks for any help getting shi7 to work on my Mac.
Best,
René
