### ISSUE TITLE
'VERSION' is not defined

### ISSUE THREAD

**Issue by akiledal** [knights-lab/shi7#69]
Hello,

I just installed shi7 for the first time using conda. When I run the `shi7_learning` command, I get an error "NameError: name 'VERSION' is not defined". 

Command run: `shi7_learning -i metagenomics_trial/S3_Fallen/ -o shi7_learn`

Full error: 
> Traceback (most recent call last):
  File "/home/akiledal/miniconda3/envs/shi7/bin/shi7_learning", line 11, in <module>
    load_entry_point('shi7==1.0.0', 'console_scripts', 'shi7_learning')()
  File "/home/akiledal/miniconda3/envs/shi7/lib/python3.8/site-packages/shi7-1.0.0-py3.8.egg/shi7/shi7_learning.py", line 249, in main
NameError: name 'VERSION' is not defined

**Comment by GabeAl** [comment]
@bhillmann @mhoutti 
Do you two conda gurus have idea what might be going on here? The latest code does not use the global variable "VERSION", so it seems to be an issue with conda syncing.

**Comment by bhillmann** [comment]
Ok @GabeAl, I updated the knights-lab conda to release v1.0.2. Can you push the updates for shi7 portable so they are now in sync? The only difference between 1.0.2 and 1.0.0 is the Makefile to include the flag `-lz`
